name: Modern Music player

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: |
    if [ -f ./gradlew ]; then
      chmod +x ./gradlew
    else
      echo "gradlew not found!"
      exit 1
    fi
    - name: Build with Gradle
      run: ./gradlew build
