name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js dependencies (if available)
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build project with Gradle
        run: ./gradlew build

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: modern-music-player-apk
          path: app/build/outputs/apk/debug/app-debug.apk
